@echo off
echo Building...
"%MSBUILD_PATH%" TestFuncLib\TestFuncLib.csproj /p:OutDir=%DEPLOYMENT_SOURCE%\TestFunc\bin\
echo Deploying files...
xcopy %DEPLOYMENT_SOURCE%\TestFunc\ %DEPLOYMENT_TARGET%\TestFunc\ /e /s /y