@echo off
echo Building...
"%MSBUILD_PATH%" TestFuncLib\TestFuncLib.csproj /p:OutDir=%DEPLOYMENT_SOURCE%\TimerTriggerCSharp1\bin\
echo Deploying files...
xcopy %DEPLOYMENT_SOURCE%\TimerTriggerCSharp1 %DEPLOYMENT_TARGET% /e /s /y